#!/bin/bash

# If it is not running iteratively, don't do anything
case $- in
    *i*) ;;
      *) echo Please run this script Iteratively, I mean use \"source\" instead of \"\./\" && exit;;
esac

# Install the dependencies
echo Installing system dependencies and libraries && echo
source $(pwd)/commands/install

# Migrations
python3 manage.py makemigrations users
python3 manage.py migrate

# Collecting statics
mkdir static-files
python manage.py collectstatic

# Run
python3 manage.py runserver